version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'rails server -b 0.0.0.0 -p 3000'
    volumes:
      - .:/another_backend_test
      - /app/tmp
    ports:
      - 3000:3000
    tty: true
    stdin_open: true